name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo mac was here
      - run: env
      - run: ls -la .
      - run: export FOO=BAR
      - run: ls -la .
      - run: |
          export FOO=BAR
          echo $FOO
          git clone https://github.com/mac2000/githubactionsdemo .
          dotnet build

# var steps = [ { run: "echo hello" } ]
# child_proccess.start("bin/foo", ["sfd", "sdf"], "/temp", env)