name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
      

# var steps = [ { run: "echo hello" } ]
# child_proccess.start("bin/foo", ["sfd", "sdf"], "/temp", env)