name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo mac was here
      - run: env
      - run: ls -la .
      - run: git clone https://github.com/mac2000/githubactionsdemo .
      - run: ls -la .
      - run: dotnet build

# var steps = [ { run: "echo hello" } ]
