name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/mac2000/githubactionsdemo .
      - run: dotnet build

      

# var steps = [ { run: "echo hello" } ]
# child_proccess.start("bin/foo", ["sfd", "sdf"], "/temp", env)