name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update && apt-get install -y curl
      - run: echo Hello, world!
      - run: echo mac was here
      - run: env
      - run: ls -la .
      - run: dotnet build

# var steps = [ { run: "echo hello" } ]
